safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /

source:      ./_source
destination: ./_site
plugins:     ./_plugins

lsi:         false
pygments:    false
markdown:    redcarpet
permalink:   /:year/:month/:day/:title.html

paginate: 10          # Posts per page on the blog index
#pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/

redcarpet:
  extensions: [fenced_code_blocks]
  render_options:
